### ISSUE TITLE
AttributeError: 'Region' object has no attribute 'to_tuple'

### ISSUE THREAD

**Issue by skyhighpn** [necarlson97/codex-ai-sublime#6]
I'm getting this error when trying to use the package, any thoughts?

Traceback (most recent call last):
  File "/home/skyhigh/.config/sublime-text-3/Installed Packages/CodexAI.sublime-package/codex_ai.py", line 47, in <lambda>
  File "/home/skyhigh/.config/sublime-text-3/Installed Packages/CodexAI.sublime-package/codex_ai.py", line 63, in handle_thread
AttributeError: 'Region' object has no attribute 'to_tuple'

**Comment by skyhighpn** [comment]
Think I figured it, that function is only in sublime 4

**Comment by skyhighpn** [comment]
This makes it compatible with sublime text 3:

        # Otherwise, we are done!
        self.view.run_command('replace_text', {
            "region": [thread.region.begin(),thread.region.end()],
            "text": thread.preText + thread.result
        })

**Comment by necarlson97** [comment]
Awesome, thank you for the report and legwork here - I will review the code tomorrow, and hopefully push a fix to main. Thanks!
